### PR TITLE
Make shlink runnable as non root 

### PR DESCRIPTION
**Pull request by owngr**
# How Shlink is setup
* Shlink version: 3.5.4
* How do you serve Shlink: Docker image

Hello there, I want to use shlink on a restrictive cluster and unfortunately I noticed that it couldn't run as non root.
https://github.com/shlinkio/shlink/issues/1132

I then noticed this issue https://github.com/shlinkio/shlink/issues/1689 and thought that I would give it a try.

I ran the test with the following docker-compose
```yaml
version: '3'

services:
    shlink:
        container_name: shlink
        ports:
          - '8080:8080'
        image: shlink-test #build locally
        user: '1000001'
        environment:
          - DEFAULT_DOMAIN=s.test
          - IS_HTTPS_ENABLED=true
          - ENALE_PERIODIC_VISIT_LOCATE=true
 ```

How the logs look with supercronic (edited cron schedule to run every minutes just for testing)
```
shlink    | [2023-04-28T12:24:24.393068+00:00] [NULL] Access.NOTICE - Worker started in /etc/shlink with ID 13
shlink    | [2023-04-28T12:24:24.393561+00:00] [NULL] Access.NOTICE - Worker started in /etc/shlink with ID 14
shlink    | [2023-04-28T12:24:24.394057+00:00] [NULL] Access.NOTICE - Worker started in /etc/shlink with ID 15
shlink    | time="2023-04-28T12:25:00Z" level=info msg=starting iteration=0 job.command="php /etc/shlink/bin/cli visit:locate -q" job.position=0 job.schedule="* * * * *"
shlink    | time="2023-04-28T12:25:00Z" level=info msg="job succeeded" iteration=0 job.command="php /etc/shlink/bin/cli visit:locate -q" job.position=0 job.schedule="* * * * *"
shlink    | time="2023-04-28T12:26:00Z" level=info msg=starting iteration=1 job.command="php /etc/shlink/bin/cli visit:locate -q" job.position=0 job.schedule="* * * * *"
```

I changed a bit the part to run it as non root, by changing the whole /etc/shlink it gives the possibility to edit php file as non-root in the docker image. By running `chmod g=u` it makes it possible to run this image as any user and not just 1001
```dockerfile
# Change the ownership of /etc/shlink to be writable, then change the user to non-root
RUN chown -R 1001 /etc/shlink
RUN chmod -R g=u /etc/shlink

USER 1001
```

### CODE REVIEW

**Comment by acelaya** [comment]
Hey @owngr. Thanks for the contribution!

FYI: There are some errors in the CI workflow, but they are not related with your changes. I will try to sort them out before merging this, just in case.

**Comment by acelaya** [comment]
Ok, I have tested this image locally, and while it works, installing supercronic introduces a quite big increase in the image size.

* With roadrunner it goes from 251MB (`develop`) to 449MB (`feature/non-root-docker`) uncompressed.
* With openswoole it goes from 216MB (`develop`) to 313MB (`feature/non-root-docker`) uncompressed.

So I'm a bit sceptical about merging this as is, specially taking into consideration the docker image should not be responsible for running cronjobs itself and I regret a bit having added that feature.

On the other hand, being able to run it as non-root is quite important, and it's annoying that I decided to favor having cronjobs over that (damn past me 😅).

I'm thinking a possible approach would be to have more docker image variations published, to allow users decide what better fits their needs:

* An image that supports cronjobs, but needs to be run as root.
* An image that is run as non-root, but does not support `ENABLE_PERIODIC_VISIT_LOCATE`.

And both should be available in openswoole and roadrunner flavors.

Since I'm working in parallel to switch from openswoole to roadrunner as the default docker runtime, I'm going to keep this on hold for now, because thatt's going to change a bit how the docker image is tagged. Once finished I will continue with the proposal above.

I will use your approach to change the user, because it is nicer that the bunch of currently commented-out lines in the `Dockerfile`. I will try to cherry pick from this if possible, to keep you as the author of those changes.

Thanks again for the time spent, and sorry this couldn't be more straighforward.

**Comment by onedr0p** [comment]
I'm only seeing the install size of around 9MB on the Alpine pkgs site.

https://pkgs.alpinelinux.org/package/edge/community/x86/supercronic

This is a static Go binary so there's no dependencies. I wonder what's really expanding the images size?

**Comment by acelaya** [comment]
Yeah, it's weird. I was not expecting that result.

In any case, I prefer to evolve this as discussed above.

Cronjobs should not be managed by this image, and it's not being broadly used, so I think the aim should be to get rid of it progressively.

**Comment by owngr** [comment]
Actually I think that the chown and chmod are expanding the image size, and therefore will still expand the image size if we make it run as non-root without supercronic.

But it is actually possible to use chown and chmod in the COPY command:
https://docs.docker.com/engine/reference/builder/#copy

```
COPY [--chown=<user>:<group>] [--chmod=<perms>] <src>... <dest>
COPY [--chown=<user>:<group>] [--chmod=<perms>] ["<src>",... "<dest>"]
```
This shouldn't change the image size as it's a single layer.

**Comment by acelaya** [comment]
Feel free to push changes if you want. I'll test it on the weekend.

I'm still more keen to the other approach, but the part about running as non-root is important, and it should not increase the image size

**Comment by owngr** [comment]
Sorry for the delay, the copy flag could not do all that I wanted, I had to do it in the builder image to reduce the size.

**Comment by acelaya** [comment]
I have pushed another PR using `COPY [--chown=<user>:<group>] ...` which I think should allow building the container for a non-root user, without a size increase.

It's done conditionally, and the docker publishing pipeline will publish a new `{version}-non-root` tag.

**Comment by acelaya** [comment]
Superseeded by https://github.com/shlinkio/shlink/pull/1785

**Pull request closed without merging**
