### PR TITLE
Replaces short-id by nano-id

### PR DESCRIPTION
**Pull request by marijnvandevoorde**
Hey there, 

According to this: https://github.com/dylang/shortid?tab=readme-ov-file, shortid has been deprecated as it's deemed unsafe. Although the PHP version looks to be better, it relies on yet other libraries and is pretty big for what it does.

NanoId is a lot simpler and smaller, so I'd suggest to switch. This should do the trick.

### CODE REVIEW

**Comment by acelaya** [comment]
Thanks! 

Yeah, I have checked this library for a replacement a couple of times in the past, but never really found anything good enough. 

This one looks like a pretty straightforward replacement if it works as it should.

**Review by acelaya — APPROVED** [review]
Thanks!

I gave this a quick test and it works quite well. Benchmarks also show this is much faster, although we are talking about ms ranges.

The failing step in the pipeline is not caused by anything introduced here, so I'll merge this and fix it after.

**Comment by marijnvandevoorde** [comment]
Thanks Alejandro, much appreciated. And indeed, it's not so much the speed but the security aspect that we care about! Thanks!

**Comment by acelaya** [comment]
I have just released Shlink 4.1.1 which includes this.

**Pull request merged**
